### ISSUE TITLE
2-2 Question 3

### ISSUE THREAD

**Issue by jdwastrack** [mdgriest/Studying-for-CS-403-Exam-02#5]
I'm not sure if he's changed it, but the current question asks how many cons cells are contained in the print value of (1 (2 . 3) . 4), which is 3.

(define x (cons 1 (cons (cons 2 3) 4)))
(println "x: " x)

(1 (2 . 3) . 4)

**Comment by mdgriest** [comment]
He did change it and we updated the question and response about six hours ago. Pulling should clear that up. Thanks!
